import { Dog, Shelter, PlatformStats } from "./types";

const today = new Date();
const subtractDays = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: "s1",
    legal_name: "Hope Animal Rescue",
    org_type: "rescue",
    verification_tier: "tier_2_trusted",
    location: { city: "Austin", state: "TX", postal_code: "78701" },
    website: "https://example.com/hope",
    active_listings: 45,
    dogs: []
  },
  {
    id: "s2",
    legal_name: "City Line Humane Society",
    org_type: "humane_society",
    verification_tier: "tier_1_verified",
    location: { city: "Denver", state: "CO", postal_code: "80202" },
    website: "https://example.com/cityline",
    active_listings: 120,
    dogs: []
  },
  {
    id: "s3",
    legal_name: "Second Chance Mutts",
    org_type: "rescue",
    verification_tier: "tier_0_self_asserted",
    location: { city: "Portland", state: "OR", postal_code: "97204" },
    website: null,
    active_listings: 12,
    dogs: []
  }
];

export const MOCK_DOGS: Dog[] = [
  {
    id: "d1",
    external_id: "ext-1",
    name: "Barnaby",
    species: "dog",
    intake_date: subtractDays(912),
    intake_age_days: 912,
    sex: "male",
    altered: "altered",
    size: "large",
    primary_breed: "Labrador Retriever",
    secondary_breed: "Pit Bull Terrier",
    is_mixed: true,
    primary_color: "Black",
    coat_length: "short",
    age_months: 60,
    weight_kg: 28,
    description: "Barnaby is a gentle giant who has been waiting patiently for over two years. He's incredibly loyal, loves to lean on his favorite people, and is very food motivated. He needs a quiet home where he can decompress.",
    adoption_fee: 0, // Sponsored
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "no",
    photo_urls: ["https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/barnaby",
    status: "adoptable",
    location: { city: "Austin", state: "TX", postal_code: "78701" },
    organization: MOCK_SHELTERS[0],
    confidence_score: 0.95
  },
  {
    id: "d2",
    external_id: "ext-2",
    name: "Luna",
    species: "dog",
    intake_date: subtractDays(640),
    intake_age_days: 640,
    sex: "female",
    altered: "altered",
    size: "medium",
    primary_breed: "Siberian Husky",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "White",
    coat_length: "medium",
    age_months: 84,
    weight_kg: 22,
    description: "Luna is a beautiful older girl who lost her home when her owner passed away. She can be vocal (classic Husky!) and loves cold weather. She prefers to be the only pet so she can soak up all your love.",
    adoption_fee: 150,
    special_needs: true,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "no",
    photo_urls: ["https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/luna",
    status: "adoptable",
    location: { city: "Denver", state: "CO", postal_code: "80202" },
    organization: MOCK_SHELTERS[1],
    confidence_score: 0.99
  },
  {
    id: "d3",
    external_id: "ext-3",
    name: "Roscoe",
    species: "dog",
    intake_date: subtractDays(455),
    intake_age_days: 455,
    sex: "male",
    altered: "altered",
    size: "large",
    primary_breed: "German Shepherd",
    secondary_breed: "Mix",
    is_mixed: true,
    primary_color: "Tan",
    coat_length: "short",
    age_months: 36,
    weight_kg: 35,
    description: "Roscoe is incredibly smart and eager to please. He knows sit, stay, paw, and down. He has high energy and needs an active family. The shelter environment is very stressful for him.",
    adoption_fee: 200,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    photo_urls: ["https://images.unsplash.com/photo-1589941013453-ec89f33b6e9e?auto=format&fit=crop&w=800&q=80"],
    listing_url: null,
    status: "adoptable",
    location: { city: "Portland", state: "OR", postal_code: "97204" },
    organization: MOCK_SHELTERS[2],
    confidence_score: 0.92
  },
  {
    id: "d4",
    external_id: "ext-4",
    name: "Daisy",
    species: "dog",
    intake_date: subtractDays(310),
    intake_age_days: 310,
    sex: "female",
    altered: "altered",
    size: "small",
    primary_breed: "Chihuahua",
    secondary_breed: "Terrier",
    is_mixed: true,
    primary_color: "Fawn",
    coat_length: "short",
    age_months: 120,
    weight_kg: 4,
    description: "Sweet senior Daisy wants nothing more than a warm lap and soft blankets. She doesn't have many teeth left but has a massive heart.",
    adoption_fee: 50,
    special_needs: true,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "no",
    photo_urls: ["https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/daisy",
    status: "adoptable",
    location: { city: "Austin", state: "TX", postal_code: "78701" },
    organization: MOCK_SHELTERS[0],
    confidence_score: 1.0
  },
  {
    id: "d5",
    external_id: "ext-5",
    name: "Buster",
    species: "dog",
    intake_date: subtractDays(275),
    intake_age_days: 275,
    sex: "male",
    altered: "altered",
    size: "medium",
    primary_breed: "Beagle",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "Tricolor",
    coat_length: "short",
    age_months: 48,
    weight_kg: 14,
    description: "Buster follows his nose everywhere! He's a merry, fun-loving, and curious dog. Needs a secure yard because if he catches a scent, he's off.",
    adoption_fee: 250,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "yes",
    photo_urls: ["https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=800&q=80"],
    listing_url: null,
    status: "adoptable",
    location: { city: "Denver", state: "CO", postal_code: "80202" },
    organization: MOCK_SHELTERS[1],
    confidence_score: 0.88
  },
  {
    id: "d6",
    external_id: "ext-6",
    name: "Apollo",
    species: "dog",
    intake_date: subtractDays(180),
    intake_age_days: 180,
    sex: "male",
    altered: "intact",
    size: "xlarge",
    primary_breed: "Great Dane",
    secondary_breed: "Mastiff",
    is_mixed: true,
    primary_color: "Brindle",
    coat_length: "short",
    age_months: 18,
    weight_kg: 55,
    description: "Big, goofy puppy trapped in a massive body. Apollo doesn't realize his size, but he's endlessly loving and eager to learn.",
    adoption_fee: 300,
    special_needs: false,
    good_with_dogs: "unknown",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    photo_urls: [], // Intentional missing photo
    listing_url: "https://example.com/adopt/apollo",
    status: "adoptable",
    location: { city: "Portland", state: "OR", postal_code: "97204" },
    organization: MOCK_SHELTERS[2],
    confidence_score: 0.8
  },
  {
    id: "d7",
    external_id: "ext-7",
    name: "Bella",
    species: "dog",
    intake_date: subtractDays(150),
    intake_age_days: 150,
    sex: "female",
    altered: "altered",
    size: "medium",
    primary_breed: "Australian Shepherd",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "Blue Merle",
    coat_length: "medium",
    age_months: 24,
    weight_kg: 20,
    description: "Highly intelligent and energetic. Bella excels at agility courses and needs a job to do.",
    adoption_fee: 350,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "unknown",
    photo_urls: ["https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/bella",
    status: "adoptable",
    location: { city: "Austin", state: "TX", postal_code: "78701" },
    organization: MOCK_SHELTERS[0],
    confidence_score: 0.96
  },
  {
    id: "d8",
    external_id: "ext-8",
    name: "Charlie",
    species: "dog",
    intake_date: subtractDays(120),
    intake_age_days: 120,
    sex: "male",
    altered: "altered",
    size: "small",
    primary_breed: "Pug",
    secondary_breed: "Mix",
    is_mixed: true,
    primary_color: "Fawn",
    coat_length: "short",
    age_months: 72,
    weight_kg: 9,
    description: "A lovable couch potato. Charlie snorts, snores, and loves belly rubs.",
    adoption_fee: 100,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "yes",
    photo_urls: ["https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80"],
    listing_url: null,
    status: "adoptable",
    location: { city: "Denver", state: "CO", postal_code: "80202" },
    organization: MOCK_SHELTERS[1],
    confidence_score: 0.94
  },
  {
    id: "d9",
    external_id: "ext-9",
    name: "Max",
    species: "dog",
    intake_date: subtractDays(90),
    intake_age_days: 90,
    sex: "male",
    altered: "altered",
    size: "large",
    primary_breed: "Boxer",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "Brindle",
    coat_length: "short",
    age_months: 12,
    weight_kg: 30,
    description: "Max is still a puppy at heart. He loves to play fetch and go for long runs.",
    adoption_fee: 250,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    photo_urls: ["https://plus.unsplash.com/premium_photo-1668208365313-094e9f735d46?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/max",
    status: "adoptable",
    location: { city: "Portland", state: "OR", postal_code: "97204" },
    organization: MOCK_SHELTERS[2],
    confidence_score: 0.9
  },
  {
    id: "d10",
    external_id: "ext-10",
    name: "Lucy",
    species: "dog",
    intake_date: subtractDays(60),
    intake_age_days: 60,
    sex: "female",
    altered: "altered",
    size: "small",
    primary_breed: "Dachshund",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "Red",
    coat_length: "short",
    age_months: 36,
    weight_kg: 6,
    description: "Lucy is a sweet and curious little girl. She loves to burrow under blankets.",
    adoption_fee: 300,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "no",
    photo_urls: ["https://images.unsplash.com/photo-1615086884396-e8b871cbedd5?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/lucy",
    status: "adoptable",
    location: { city: "Austin", state: "TX", postal_code: "78701" },
    organization: MOCK_SHELTERS[0],
    confidence_score: 0.98
  },
  {
    id: "d11",
    external_id: "ext-11",
    name: "Cooper",
    species: "dog",
    intake_date: subtractDays(45),
    intake_age_days: 45,
    sex: "male",
    altered: "altered",
    size: "medium",
    primary_breed: "Golden Retriever",
    secondary_breed: "Mix",
    is_mixed: true,
    primary_color: "Golden",
    coat_length: "medium",
    age_months: 8,
    weight_kg: 18,
    description: "A happy-go-lucky puppy! Cooper needs basic training but has a heart of gold.",
    adoption_fee: 400,
    special_needs: false,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    photo_urls: ["https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=800&q=80"],
    listing_url: null,
    status: "adoptable",
    location: { city: "Denver", state: "CO", postal_code: "80202" },
    organization: MOCK_SHELTERS[1],
    confidence_score: 0.85
  },
  {
    id: "d12",
    external_id: "ext-12",
    name: "Sadie",
    species: "dog",
    intake_date: subtractDays(30),
    intake_age_days: 30,
    sex: "female",
    altered: "altered",
    size: "large",
    primary_breed: "Rottweiler",
    secondary_breed: null,
    is_mixed: false,
    primary_color: "Black/Tan",
    coat_length: "short",
    age_months: 60,
    weight_kg: 40,
    description: "Sadie is a gentle soul who takes a while to warm up to strangers.",
    adoption_fee: 150,
    special_needs: true,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "no",
    photo_urls: ["https://images.unsplash.com/photo-1563460459582-8bc602ad435e?auto=format&fit=crop&w=800&q=80"],
    listing_url: "https://example.com/adopt/sadie",
    status: "adoptable",
    location: { city: "Portland", state: "OR", postal_code: "97204" },
    organization: MOCK_SHELTERS[2],
    confidence_score: 0.99
  }
];

export const MOCK_STATS: PlatformStats = {
  total_dogs: MOCK_DOGS.length + 1542,
  total_shelters: MOCK_SHELTERS.length + 84,
  adoptions_this_month: 231,
  avg_wait_days: 142,
  longest_wait_days: 912
};

// Also attach dogs to shelters for the profile view
MOCK_SHELTERS[0].dogs = MOCK_DOGS.filter(d => d.organization.id === MOCK_SHELTERS[0].id);
MOCK_SHELTERS[1].dogs = MOCK_DOGS.filter(d => d.organization.id === MOCK_SHELTERS[1].id);
MOCK_SHELTERS[2].dogs = MOCK_DOGS.filter(d => d.organization.id === MOCK_SHELTERS[2].id);
