/**
 * Mock seed data for development.
 * Used when NEXT_PUBLIC_API_URL is not set or API is unreachable.
 * 20 dogs across 5 shelters with realistic data.
 */
import type { DogSummary, DogDetail, PlatformStats, FeaturedResponse, ShelterProfile, DogPage } from "./api";

const today = new Date();
function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

// ---- Shelters ----
export const MOCK_SHELTERS: ShelterProfile[] = [
  {
    id: "s1",
    legal_name: "Hope Animal Rescue",
    org_type: "rescue",
    verification_tier: "tier_2_trusted",
    city: "Austin",
    state: "TX",
    postal_code: "78701",
    website: "https://example.com/hope",
    active_listings: 45,
    created_at: "2024-01-15",
  },
  {
    id: "s2",
    legal_name: "City Line Humane Society",
    org_type: "humane_society",
    verification_tier: "tier_1_verified",
    city: "Denver",
    state: "CO",
    postal_code: "80202",
    website: "https://example.com/cityline",
    active_listings: 120,
    created_at: "2023-06-01",
  },
  {
    id: "s3",
    legal_name: "Second Chance Mutts",
    org_type: "rescue",
    verification_tier: "tier_0_self_asserted",
    city: "Portland",
    state: "OR",
    postal_code: "97204",
    website: null,
    active_listings: 12,
    created_at: "2025-03-10",
  },
  {
    id: "s4",
    legal_name: "South Shore SPCA",
    org_type: "spca",
    verification_tier: "tier_1_verified",
    city: "Brockton",
    state: "MA",
    postal_code: "02301",
    website: "https://example.com/ssspca",
    active_listings: 30,
    created_at: "2024-09-01",
  },
  {
    id: "s5",
    legal_name: "Heartland Foster Network",
    org_type: "foster_network",
    verification_tier: "tier_2_trusted",
    city: "Chicago",
    state: "IL",
    postal_code: "60601",
    website: "https://example.com/heartland",
    active_listings: 65,
    created_at: "2023-11-20",
  },
];

// ---- Dogs ----
export const MOCK_DOGS: DogSummary[] = [
  {
    id: "d1",
    name: "Barnaby",
    species: "dog",
    primary_breed: "Labrador Retriever",
    secondary_breed: "Pit Bull Terrier",
    is_mixed: true,
    sex: "male",
    size: "large",
    age_months: 60,
    sac_age_group: "adult",
    primary_color: "Black",
    primary_photo_url: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80",
    days_waiting: 912,
    intake_date: daysAgo(912),
    adoption_fee: 0,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "no",
    special_needs: false,
    location_city: "Austin",
    location_state: "TX",
    shelter_name: "Hope Animal Rescue",
    status: "adoptable",
  },
  {
    id: "d2",
    name: "Luna",
    species: "dog",
    primary_breed: "Siberian Husky",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "medium",
    age_months: 84,
    sac_age_group: "adult",
    primary_color: "White",
    primary_photo_url: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=800&q=80",
    days_waiting: 640,
    intake_date: daysAgo(640),
    adoption_fee: 150,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "no",
    special_needs: true,
    location_city: "Denver",
    location_state: "CO",
    shelter_name: "City Line Humane Society",
    status: "adoptable",
  },
  {
    id: "d3",
    name: "Roscoe",
    species: "dog",
    primary_breed: "German Shepherd",
    secondary_breed: null,
    is_mixed: true,
    sex: "male",
    size: "large",
    age_months: 36,
    sac_age_group: "adult",
    primary_color: "Tan",
    primary_photo_url: "https://images.unsplash.com/photo-1589941013453-ec89f33b6e9e?auto=format&fit=crop&w=800&q=80",
    days_waiting: 455,
    intake_date: daysAgo(455),
    adoption_fee: 200,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Portland",
    location_state: "OR",
    shelter_name: "Second Chance Mutts",
    status: "adoptable",
  },
  {
    id: "d4",
    name: "Daisy",
    species: "dog",
    primary_breed: "Chihuahua",
    secondary_breed: "Terrier",
    is_mixed: true,
    sex: "female",
    size: "small",
    age_months: 120,
    sac_age_group: "adult",
    primary_color: "Fawn",
    primary_photo_url: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80",
    days_waiting: 310,
    intake_date: daysAgo(310),
    adoption_fee: 50,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "no",
    special_needs: true,
    location_city: "Austin",
    location_state: "TX",
    shelter_name: "Hope Animal Rescue",
    status: "adoptable",
  },
  {
    id: "d5",
    name: "Buster",
    species: "dog",
    primary_breed: "Beagle",
    secondary_breed: null,
    is_mixed: false,
    sex: "male",
    size: "medium",
    age_months: 48,
    sac_age_group: "adult",
    primary_color: "Tricolor",
    primary_photo_url: "https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=800&q=80",
    days_waiting: 275,
    intake_date: daysAgo(275),
    adoption_fee: 250,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Denver",
    location_state: "CO",
    shelter_name: "City Line Humane Society",
    status: "adoptable",
  },
  {
    id: "d6",
    name: "Apollo",
    species: "dog",
    primary_breed: "Great Dane",
    secondary_breed: "Mastiff",
    is_mixed: true,
    sex: "male",
    size: "xlarge",
    age_months: 18,
    sac_age_group: "adult",
    primary_color: "Brindle",
    primary_photo_url: null,
    days_waiting: 180,
    intake_date: daysAgo(180),
    adoption_fee: 300,
    good_with_dogs: "unknown",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Portland",
    location_state: "OR",
    shelter_name: "Second Chance Mutts",
    status: "adoptable",
  },
  {
    id: "d7",
    name: "Bella",
    species: "dog",
    primary_breed: "Australian Shepherd",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "medium",
    age_months: 24,
    sac_age_group: "adult",
    primary_color: "Blue Merle",
    primary_photo_url: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80",
    days_waiting: 150,
    intake_date: daysAgo(150),
    adoption_fee: 350,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "unknown",
    special_needs: false,
    location_city: "Austin",
    location_state: "TX",
    shelter_name: "Hope Animal Rescue",
    status: "adoptable",
  },
  {
    id: "d8",
    name: "Charlie",
    species: "dog",
    primary_breed: "Pug",
    secondary_breed: null,
    is_mixed: true,
    sex: "male",
    size: "small",
    age_months: 72,
    sac_age_group: "adult",
    primary_color: "Fawn",
    primary_photo_url: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80",
    days_waiting: 120,
    intake_date: daysAgo(120),
    adoption_fee: 100,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Denver",
    location_state: "CO",
    shelter_name: "City Line Humane Society",
    status: "adoptable",
  },
  {
    id: "d9",
    name: "Max",
    species: "dog",
    primary_breed: "Boxer",
    secondary_breed: null,
    is_mixed: false,
    sex: "male",
    size: "large",
    age_months: 12,
    sac_age_group: "adult",
    primary_color: "Brindle",
    primary_photo_url: "https://plus.unsplash.com/premium_photo-1668208365313-094e9f735d46?auto=format&fit=crop&w=800&q=80",
    days_waiting: 90,
    intake_date: daysAgo(90),
    adoption_fee: 250,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Portland",
    location_state: "OR",
    shelter_name: "Second Chance Mutts",
    status: "adoptable",
  },
  {
    id: "d10",
    name: "Lucy",
    species: "dog",
    primary_breed: "Dachshund",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "small",
    age_months: 36,
    sac_age_group: "adult",
    primary_color: "Red",
    primary_photo_url: "https://images.unsplash.com/photo-1615086884396-e8b871cbedd5?auto=format&fit=crop&w=800&q=80",
    days_waiting: 60,
    intake_date: daysAgo(60),
    adoption_fee: 300,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "no",
    special_needs: false,
    location_city: "Austin",
    location_state: "TX",
    shelter_name: "Hope Animal Rescue",
    status: "adoptable",
  },
  {
    id: "d11",
    name: "Cooper",
    species: "dog",
    primary_breed: "Golden Retriever",
    secondary_breed: null,
    is_mixed: true,
    sex: "male",
    size: "medium",
    age_months: 8,
    sac_age_group: "under_5_months",
    primary_color: "Golden",
    primary_photo_url: "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=800&q=80",
    days_waiting: 45,
    intake_date: daysAgo(45),
    adoption_fee: 400,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Denver",
    location_state: "CO",
    shelter_name: "City Line Humane Society",
    status: "adoptable",
  },
  {
    id: "d12",
    name: "Sadie",
    species: "dog",
    primary_breed: "Rottweiler",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "large",
    age_months: 60,
    sac_age_group: "adult",
    primary_color: "Black/Tan",
    primary_photo_url: "https://images.unsplash.com/photo-1563460459582-8bc602ad435e?auto=format&fit=crop&w=800&q=80",
    days_waiting: 30,
    intake_date: daysAgo(30),
    adoption_fee: 150,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "no",
    special_needs: true,
    location_city: "Portland",
    location_state: "OR",
    shelter_name: "Second Chance Mutts",
    status: "adoptable",
  },
  {
    id: "d13",
    name: "Penny",
    species: "dog",
    primary_breed: "Cocker Spaniel",
    secondary_breed: "Poodle",
    is_mixed: true,
    sex: "female",
    size: "small",
    age_months: 48,
    sac_age_group: "adult",
    primary_color: "Apricot",
    primary_photo_url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80",
    days_waiting: 520,
    intake_date: daysAgo(520),
    adoption_fee: 175,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Brockton",
    location_state: "MA",
    shelter_name: "South Shore SPCA",
    status: "adoptable",
  },
  {
    id: "d14",
    name: "Duke",
    species: "dog",
    primary_breed: "Cane Corso",
    secondary_breed: null,
    is_mixed: false,
    sex: "male",
    size: "xlarge",
    age_months: 30,
    sac_age_group: "adult",
    primary_color: "Gray",
    primary_photo_url: "https://images.unsplash.com/photo-1587559070757-f72a388edbba?auto=format&fit=crop&w=800&q=80",
    days_waiting: 390,
    intake_date: daysAgo(390),
    adoption_fee: 200,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "unknown",
    special_needs: false,
    location_city: "Chicago",
    location_state: "IL",
    shelter_name: "Heartland Foster Network",
    status: "adoptable",
  },
  {
    id: "d15",
    name: "Rosie",
    species: "dog",
    primary_breed: "Shih Tzu",
    secondary_breed: "Maltese",
    is_mixed: true,
    sex: "female",
    size: "small",
    age_months: 96,
    sac_age_group: "adult",
    primary_color: "White/Brown",
    primary_photo_url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80",
    days_waiting: 210,
    intake_date: daysAgo(210),
    adoption_fee: 75,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "no",
    special_needs: true,
    location_city: "Brockton",
    location_state: "MA",
    shelter_name: "South Shore SPCA",
    status: "adoptable",
  },
  {
    id: "d16",
    name: "Tank",
    species: "dog",
    primary_breed: "American Bulldog",
    secondary_breed: null,
    is_mixed: false,
    sex: "male",
    size: "large",
    age_months: 42,
    sac_age_group: "adult",
    primary_color: "White",
    primary_photo_url: "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?auto=format&fit=crop&w=800&q=80",
    days_waiting: 365,
    intake_date: daysAgo(365),
    adoption_fee: 0,
    good_with_dogs: "unknown",
    good_with_cats: "no",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Chicago",
    location_state: "IL",
    shelter_name: "Heartland Foster Network",
    status: "adoptable",
  },
  {
    id: "d17",
    name: "Ginger",
    species: "dog",
    primary_breed: "Irish Setter",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "large",
    age_months: 60,
    sac_age_group: "adult",
    primary_color: "Red",
    primary_photo_url: "https://images.unsplash.com/photo-1546238232-20216dec9f72?auto=format&fit=crop&w=800&q=80",
    days_waiting: 140,
    intake_date: daysAgo(140),
    adoption_fee: 225,
    good_with_dogs: "yes",
    good_with_cats: "yes",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Brockton",
    location_state: "MA",
    shelter_name: "South Shore SPCA",
    status: "adoptable",
  },
  {
    id: "d18",
    name: "Zeus",
    species: "dog",
    primary_breed: "Doberman Pinscher",
    secondary_breed: null,
    is_mixed: false,
    sex: "male",
    size: "large",
    age_months: 24,
    sac_age_group: "adult",
    primary_color: "Black/Rust",
    primary_photo_url: "https://images.unsplash.com/photo-1553882809-a4f57e59501d?auto=format&fit=crop&w=800&q=80",
    days_waiting: 85,
    intake_date: daysAgo(85),
    adoption_fee: 350,
    good_with_dogs: "yes",
    good_with_cats: "no",
    good_with_kids: "unknown",
    special_needs: false,
    location_city: "Chicago",
    location_state: "IL",
    shelter_name: "Heartland Foster Network",
    status: "adoptable",
  },
  {
    id: "d19",
    name: "Mochi",
    species: "dog",
    primary_breed: "Shiba Inu",
    secondary_breed: null,
    is_mixed: false,
    sex: "female",
    size: "medium",
    age_months: 18,
    sac_age_group: "adult",
    primary_color: "Red Sesame",
    primary_photo_url: "https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?auto=format&fit=crop&w=800&q=80",
    days_waiting: 55,
    intake_date: daysAgo(55),
    adoption_fee: 450,
    good_with_dogs: "no",
    good_with_cats: "no",
    good_with_kids: "unknown",
    special_needs: false,
    location_city: "Austin",
    location_state: "TX",
    shelter_name: "Hope Animal Rescue",
    status: "adoptable",
  },
  {
    id: "d20",
    name: "Buddy",
    species: "dog",
    primary_breed: "Border Collie",
    secondary_breed: "Lab",
    is_mixed: true,
    sex: "male",
    size: "medium",
    age_months: 15,
    sac_age_group: "adult",
    primary_color: "Black/White",
    primary_photo_url: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc8f9b?auto=format&fit=crop&w=800&q=80",
    days_waiting: 25,
    intake_date: daysAgo(25),
    adoption_fee: 375,
    good_with_dogs: "yes",
    good_with_cats: "unknown",
    good_with_kids: "yes",
    special_needs: false,
    location_city: "Brockton",
    location_state: "MA",
    shelter_name: "South Shore SPCA",
    status: "adoptable",
  },
];

// ---- Dog Details (extends summary with description etc.) ----
const DOG_DESCRIPTIONS: Record<string, string> = {
  d1: "Barnaby is a gentle giant who has been waiting patiently for over two years. He's incredibly loyal, loves to lean on his favorite people, and is very food motivated. He needs a quiet home where he can decompress.",
  d2: "Luna is a beautiful older girl who lost her home when her owner passed away. She can be vocal (classic Husky!) and loves cold weather. She prefers to be the only pet so she can soak up all your love.",
  d3: "Roscoe is incredibly smart and eager to please. He knows sit, stay, paw, and down. He has high energy and needs an active family. The shelter environment is very stressful for him.",
  d4: "Sweet senior Daisy wants nothing more than a warm lap and soft blankets. She doesn't have many teeth left but has a massive heart.",
  d5: "Buster follows his nose everywhere! He's a merry, fun-loving, and curious dog. Needs a secure yard because if he catches a scent, he's off.",
  d6: "Big, goofy puppy trapped in a massive body. Apollo doesn't realize his size, but he's endlessly loving and eager to learn.",
  d7: "Highly intelligent and energetic. Bella excels at agility courses and needs a job to do.",
  d8: "A lovable couch potato. Charlie snorts, snores, and loves belly rubs.",
  d9: "Max is still a puppy at heart. He loves to play fetch and go for long runs.",
  d10: "Lucy is a sweet and curious little girl. She loves to burrow under blankets.",
  d11: "A happy-go-lucky puppy! Cooper needs basic training but has a heart of gold.",
  d12: "Sadie is a gentle soul who takes a while to warm up to strangers.",
  d13: "Penny is the sweetest cockapoo you'll ever meet. She loves everyone and everything. Previously a therapy dog, she has impeccable manners.",
  d14: "Duke is a big, protective boy who needs an experienced owner. He's incredibly bonded to his person once he trusts you. Not for first-time owners.",
  d15: "Rosie is a senior sweetheart with a heart murmur that's being managed with medication. She's calm, quiet, and just wants a warm bed.",
  d16: "Tank is a total marshmallow despite his name. He was found as a stray and has been waiting a full year for someone to see past his breed label.",
  d17: "Ginger is a gorgeous Irish Setter who loves long walks and swimming. She's an absolute sweetheart with everyone she meets.",
  d18: "Zeus is a sleek, athletic boy who needs an active home. He loves running and would make a great jogging companion.",
  d19: "Mochi is a sassy Shiba who does things on her own terms. She's independent but affectionate once she decides you're worthy.",
  d20: "Buddy is a high-energy mix who needs a job. He'd excel at agility, herding, or any dog sport. Very eager to learn.",
};

const SHELTER_MAP: Record<string, { id: string; name: string; website: string | null }> = {
  "Hope Animal Rescue": { id: "s1", name: "Hope Animal Rescue", website: "https://example.com/hope" },
  "City Line Humane Society": { id: "s2", name: "City Line Humane Society", website: "https://example.com/cityline" },
  "Second Chance Mutts": { id: "s3", name: "Second Chance Mutts", website: null },
  "South Shore SPCA": { id: "s4", name: "South Shore SPCA", website: "https://example.com/ssspca" },
  "Heartland Foster Network": { id: "s5", name: "Heartland Foster Network", website: "https://example.com/heartland" },
};

export function getMockDogDetail(id: string): DogDetail | null {
  const summary = MOCK_DOGS.find((d) => d.id === id);
  if (!summary) return null;
  const shelter = SHELTER_MAP[summary.shelter_name];
  return {
    ...summary,
    description: DOG_DESCRIPTIONS[id] || "",
    coat_length: "short",
    weight_kg: Math.round(10 + Math.random() * 40),
    altered: Math.random() > 0.3 ? "altered" : "intact",
    photo_urls: summary.primary_photo_url ? [summary.primary_photo_url] : [],
    listing_url: Math.random() > 0.3 ? `https://example.com/adopt/${summary.name.toLowerCase()}` : null,
    intake_type: "stray_at_large",
    location_lat: null,
    location_lng: null,
    location_postal_code: "00000",
    first_listed_at: summary.intake_date,
    organization_id: shelter?.id || "s1",
    shelter_website: shelter?.website || null,
  };
}

export function getMockDogs(filters: Record<string, string | undefined> = {}): DogPage {
  let items = [...MOCK_DOGS];

  // Filter by breed
  if (filters.breed) {
    const b = filters.breed.toLowerCase();
    items = items.filter(
      (d) =>
        d.primary_breed.toLowerCase().includes(b) ||
        (d.secondary_breed && d.secondary_breed.toLowerCase().includes(b))
    );
  }

  // Filter by size
  if (filters.size) {
    items = items.filter((d) => d.size === filters.size);
  }

  // Filter by state
  if (filters.state) {
    items = items.filter((d) => d.location_state === filters.state!.toUpperCase());
  }

  // Sort
  const sort = filters.sort || "days_waiting_desc";
  if (sort === "days_waiting_desc") {
    items.sort((a, b) => b.days_waiting - a.days_waiting);
  } else if (sort === "days_waiting_asc") {
    items.sort((a, b) => a.days_waiting - b.days_waiting);
  } else if (sort === "recently_added") {
    items.sort((a, b) => a.days_waiting - b.days_waiting);
  } else if (sort === "name_asc") {
    items.sort((a, b) => a.name.localeCompare(b.name));
  }

  // Paginate
  const page = parseInt(filters.page || "1", 10);
  const perPage = parseInt(filters.per_page || "12", 10);
  const start = (page - 1) * perPage;
  const paged = items.slice(start, start + perPage);

  return {
    items: paged,
    pagination: {
      total: items.length,
      page,
      per_page: perPage,
      total_pages: Math.ceil(items.length / perPage),
      has_next: start + perPage < items.length,
      has_prev: page > 1,
    },
  };
}

export const MOCK_STATS: PlatformStats = {
  total_dogs: MOCK_DOGS.length + 1542,
  total_shelters: MOCK_SHELTERS.length + 84,
  avg_wait_days: 142,
  longest_wait_days: 912,
  adoptions_this_month: 231,
};

export function getMockFeatured(): FeaturedResponse {
  const sorted = [...MOCK_DOGS].sort((a, b) => b.days_waiting - a.days_waiting);
  return {
    longest_waiting: sorted.slice(0, 4),
    recently_added: [...MOCK_DOGS].sort((a, b) => a.days_waiting - b.days_waiting).slice(0, 4),
  };
}

export function getMockShelter(id: string): (ShelterProfile & { dogs: DogSummary[] }) | null {
  const shelter = MOCK_SHELTERS.find((s) => s.id === id);
  if (!shelter) return null;
  const dogs = MOCK_DOGS.filter((d) => {
    const s = SHELTER_MAP[d.shelter_name];
    return s && s.id === id;
  }).sort((a, b) => b.days_waiting - a.days_waiting);
  return { ...shelter, dogs };
}
